CHARMAP "\n", $fe ;next line

CHARMAP " ", $00
CHARMAP "0", $22
CHARMAP "'", $be
CHARMAP "A", $bf
CHARMAP "B", $c0
CHARMAP "C", $c1
CHARMAP "D", $c2
CHARMAP "E", $c3
CHARMAP "F", $c4
CHARMAP "G", $c5
CHARMAP "H", $c6
CHARMAP "I", $c7
CHARMAP "J", $c8
CHARMAP "K", $c9
CHARMAP "L", $ca
CHARMAP "M", $cb
CHARMAP "N", $cc
CHARMAP "O", $cd
CHARMAP "P", $ce
CHARMAP "Q", $cf
CHARMAP "R", $d0
CHARMAP "S", $d1
CHARMAP "T", $d2
CHARMAP "U", $d3
CHARMAP "V", $d4
CHARMAP "W", $d5
CHARMAP "X", $d6
CHARMAP "Y", $d7
CHARMAP "Z", $d8
CHARMAP ".", $dd
CHARMAP ",", $de
CHARMAP "\"", $e0
CHARMAP "!", $e1
CHARMAP "?", $e2
CHARMAP "-", $e3
CHARMAP "…", $e4
CHARMAP ":", $e5
CHARMAP "0", $f4
CHARMAP "1", $f5
CHARMAP "2", $f6
CHARMAP "3", $f7
CHARMAP "4", $f8
CHARMAP "5", $f9
CHARMAP "6", $fa
CHARMAP "7", $fb
CHARMAP "8", $fc
CHARMAP "9", $fd
